kind: pipeline
type: kubernetes
name: pi-kube

steps:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: jtbarclay/pgtest
    tags: ["${DRONE_COMMIT_SHA:0:7}", "latest"]

- name: deploy
  image: jtbarclay/drone-kubernetes:latest
  settings:
    kubernetes_server:
      from_secret: k3s_server
    kubernetes_cert:
      from_secret: k3s_cert
    kubernetes_token:
      from_secret: k3s_token
    deployment: haldane-server
    repo: jtbarclay/haldane
    container: haldane-server
    namespace: drone
    tag:                 
      - ${DRONE_COMMIT_SHA:0:7}

node_selector:
  kubernetes.io/arch: arm64