apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgtest-deploy
  namespace: pgtest

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: pgtest-deploy
  namespace: pgtest
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","patch","update"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pgtest-deploy
  namespace: pgtest
subjects:
  - kind: ServiceAccount
    name: pgtest-deploy
    namespace: pgtest
roleRef:
  kind: Role
  name: pgtest-deploy
  apiGroup: rbac.authorization.k8s.io
